packages:
  - "apps/*"
  - "packages/*"

catalog:
  "react": ^18.3.1
  "react-dom": ^18.3.1
  "zod": ^3.23.8
  "@types/react": ^18.3.11
  "@types/react-dom": ^18.3.1
  "eslint": ^8.57.0
  "prettier": ^3.3.3
  "sanity": ^3.61.0
  "typescript": ^5.6.3
